In [6]:
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.resnet50 import preprocess_input
from keras.models import load_model

import numpy as np
import os
import random
import shutil
import PIL
from PIL import Image
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix

In [5]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(480, 640, 3)))
model.add(layers.Conv2D(64, (3, 3), activation='relu', groups=1))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(128, (3, 3), activation='relu', groups=1))
model.add(layers.MaxPooling2D((2, 2)))

model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(822, activation='softmax'))

# Restore the weights
model.load_weights("model1.keras")
model.compile()

In [31]:
directory = "../Segmented-Casia-Iris-Lamp-New-Test"

batch_size = 32
img_height = 480
img_width = 640
input_shape = (img_height, img_width, 3) 

test_datagen = ImageDataGenerator()

test_generator = test_datagen.flow_from_directory(
    directory,
    target_size=(img_height, img_width),
    class_mode='sparse')

labels = test_generator.classes

Found 4902 images belonging to 1 classes.


In [32]:
predictions = model.predict(test_generator, labels)

154/154 [==============================] - 265s 2s/step


In [33]:
print(predictions)

[[5.8659307e-11 1.0234588e-14 5.3257454e-06 ... 8.0186794e-07
  4.7885630e-19 5.4503003e-19]
 [7.6267173e-23 1.9277191e-11 7.5290529e-20 ... 2.9753968e-15
  8.8243243e-24 6.1781895e-23]
 [2.3274317e-06 9.7041820e-06 6.1385890e-06 ... 4.8864340e-15
  5.6272094e-16 1.0557174e-16]
 ...
 [3.5772802e-09 5.1022062e-07 3.2468882e-11 ... 9.8763174e-08
  6.4767578e-15 8.0233095e-14]
 [3.9412241e-17 5.4558297e-21 1.3035676e-14 ... 5.6360197e-14
  6.9046294e-37 2.0067027e-38]
 [1.8082134e-03 1.7329678e-02 1.3917883e-06 ... 1.4366545e-08
  4.3013688e-13 1.7375860e-12]]


In [34]:
# Convert predictions to class labels
predicted_classes = np.argmax(predictions, axis=1)

# Get true labels
true_labels = test_generator.classes

# Calculate accuracy
accuracy = accuracy_score(true_labels, predicted_classes)
print("Accuracy:", accuracy)

# Calculate precision, recall, and F1-score
precision, recall, f1_score, _ = precision_recall_fscore_support(true_labels, predicted_classes, average='weighted')
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1_score)

# Calculate confusion matrix
conf_matrix = confusion_matrix(true_labels, predicted_classes)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.0016319869441044472
Precision: 0.0014950166112956812
Recall: 0.0016319869441044472
F1-score: 0.0014803486211373484
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [2]:
model1 = models.Sequential()
model1.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(480, 640, 3)))
model1.add(layers.MaxPooling2D((2, 2)))
model1.add(layers.Conv2D(64, (3, 3), activation='relu', groups=1))
model1.add(layers.MaxPooling2D((2, 2)))
model1.add(layers.Conv2D(64, (3, 3), activation='relu', groups=1))
model1.add(layers.MaxPooling2D((2, 2)))
model1.add(layers.Conv2D(64, (3, 3), activation='relu', groups=1))
model1.add(layers.MaxPooling2D((2, 2)))
model1.add(layers.Flatten())
model1.add(layers.Dense(128, activation='relu'))
model1.add(layers.Dense(820, activation='softmax'))

model1.load_weights("model4.keras")
model1.compile()

directory = "../Segmented-Casia-Iris-Lamp-New-Test"

batch_size = 32
img_height = 480
img_width = 640
input_shape = (img_height, img_width, 3) 

test_datagen = ImageDataGenerator()

test_generator = test_datagen.flow_from_directory(
    directory,
    target_size=(img_height, img_width),
    class_mode='sparse')

labels = test_generator.classes

Found 4902 images belonging to 820 classes.


In [8]:
predictions1 = model1.predict(test_generator, labels)

154/154 [==============================] - 76s 489ms/step


In [9]:
# Convert predictions to class labels
predicted_classes1 = np.argmax(predictions1, axis=1)

# Get true labels
true_labels = test_generator.classes

# Calculate accuracy
accuracy = accuracy_score(true_labels, predicted_classes1)
print("Accuracy:", accuracy)

# Calculate precision, recall, and F1-score
precision, recall, f1_score, _ = precision_recall_fscore_support(true_labels, predicted_classes1, average='weighted')
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1_score)

# Calculate confusion matrix
conf_matrix = confusion_matrix(true_labels, predicted_classes1)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.0012239902080783353
Precision: 0.0012662470128810398
Recall: 0.0012239902080783353
F1-score: 0.001234791320470635
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
